apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: secure-app
spec:
  selector:
    app: secure-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
